name: Publish to Docker hub
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image:tag
      run: docker build . --file Dockerfile --tag tlnk/mgm-infra:$(git rev-parse --short $GITHUB_SHA) --tag tlnk/mgm-infra:latest
    - name: Login Docker hub
      run: docker login --username ${{ secrets.DOCKER_HUB_USER }} --password ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Publish image:tag on Docker hub
      run: docker push tlnk/mgm-infra:$(git rev-parse --short $GITHUB_SHA)
    - name: Publish image:latest on Docker hub
      run: docker push tlnk/mgm-infra:latest